[deploy]
bucket = 'cfn-artifacts-bckt'
region = 'ap-south-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://mycruddur.site'
EnvBackendUrl = 'https://api.mycruddur.site'
BuildSpec = 'backend-flask/buildspec.yml'
DDBMessageTable = 'CrdDdb-DynamoDBTable-18MYW2UXZQRVL'
